version: "3.9"

services:
   api:
      image: node
      build:
         context: ./api
      volumes:
         - /api/node_modules
         - ./api/src:/src
      ports:
         - "3001:3001"
      environment:
         PORT: 3001
   client:
      image: react
      build:
         context: ./client/
      ports:
         - "3000:3000"
